sudo: required

language: minimal

services:
  - docker

before_install:
  - docker build -t test_wrattler_examples -f Dockerfile_local .

script:
  - docker run test_wrattler_examples /bin/bash -c "Rscript run-tests.r"
