FROM wrattler/wrattler_r_service_base:latest

## AI assistants
RUN wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb
RUN apt-get update; apt-get install -y apt-transport-https; apt-get update; apt-get install -y dotnet-hosting-2.0.6
RUN apt-get install -y dotnet-sdk-2.1
RUN Rscript -e "install.packages(\"lpSolve\",repos=\"http://cran.us.r-project.org\")"
RUN Rscript -e "devtools::install_github(\"tpetricek/datadiff\") "

RUN Rscript -e "install.packages('reshape2')"

## Python (for python service and datastore)

RUN apt-get update; apt-get install -y python3
RUN apt-get update; apt-get install -y python3-pip
RUN apt-get update; apt-get install -y locales
RUN apt-get update; apt-get install -y openssl
RUN apt-get update; apt-get install -y libssl-dev

# Set the locale
RUN sed -i -e 's/# en_GB.UTF-8 UTF-8/en_GB.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen
ENV LANG en_GB.UTF-8
ENV LANGUAGE en_GB:en
ENV LC_ALL en_GB.UTF-8

RUN pip3 install --upgrade pip
RUN pip3 install wrattler-python-service==0.7
RUN pip3 install wrattler-data-store==0.5.1

## Client dependencies
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get install -y nodejs
RUN curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install -y yarn
RUN npm install http-server -g

## Jupyterlab dependencies
RUN apt-get update; apt-get install -y python-gi-cairo libcairo2-dev
RUN pip3 install --no-cache-dir notebook==5.*
RUN pip3 install jupyter-server-proxy
RUN pip3 install jupyterlab==1.2.3
RUN pip3 install pycairo
RUN yarn add typescript

## AI assistant python dependencies
RUN pip3 install sklearn mpltools greenery clevercsv==0.4.3

## Install SVN to allow us to checkout the resources directory directly
RUN apt-get update
RUN apt-get install -y apache2
RUN apt-get install -y subversion libapache2-mod-svn libapache2-svn libsvn-dev
RUN a2enmod dav dav_svn
RUN service apache2 restart

## Checkout Wrattler and switch to branch with AI-assistants
RUN git clone https://github.com/wrattler/wrattler; cd wrattler; git checkout develop; cd -;

# AI assistants
ENV DATASTORE_URI http://localhost:7102
RUN dotnet restore wrattler/aiassistants/server/
RUN dotnet build wrattler/aiassistants/server/

# Client
RUN cd wrattler/client; yarn; yarn build; cp build/wrattler-app.js public/; cd -

# Jupyterlab
RUN cd wrattler/jupyterlab_wrattler; yarn install; jupyter labextension link .; jupyter labextension install;  jlpm run build; cd -;

CMD ["/bin/bash"]
