FROM wrattler/wrattler_base:v0.5

# install AI assistants here to avoid clash (permissions) with binder version
# AI assistants
ENV DATASTORE_URI http://localhost:7102
RUN dotnet restore /wrattler/aiassistants/server/
RUN dotnet build /wrattler/aiassistants/server/


# Copy current directory to docker image
ADD . /app
WORKDIR /app
# Install services so they can be started by jupyter server proxy
RUN cd /app/binder; pip install .
# Script to start running the services
RUN chmod a+x start-services
ENTRYPOINT ["./start-services"]
