#!/usr/bin/env python

"""
Launcher script for Wrattler.   Assume the user has Docker/docker-compose.
This script basically just runs the docker-compose commands to build the images
and start the containers, and parses the output to get the jupyterlab URL,
then uses webbrowser.open() to navigate there.
"""

import os
import sys
import time
import re
import webbrowser

if os.name == "posix":
   TMPDIR = "/tmp"
   LAUNCH_CMD = "docker-compose up >& {} &"
else:
   TMPDIR = "%TMP%"
   LAUNCH_CMD = "start /B docker-compose up > {} 2>&1"


LOGFILE = os.path.join(TMPDIR,"docker.log")
HOST = "localhost"
PORT = 8889
TIMEOUT = 20


if __name__ == "__main__":
   print("Building docker images")
   os.system("docker-compose build")
   print("Launching docker containers")
   os.system(LAUNCH_CMD.format(LOGFILE))
   for i in range(TIMEOUT):
      ## parse the log to see if we have a URL for Jupyterlab
      token = None
      try:
         input_file = open(LOGFILE)
         for line in input_file.readlines():
            if '{}/?token'.format(PORT) in line:
               token_search = re.search("token=([\w]+)",line)
               if token_search:
                  token = token_search.groups()[0]
      except:
         pass
      if token:
         url = "http://{}:{}/?token={}".format(HOST, PORT, token)
         wrattler_ready = True
         print("Wrattler is ready - going to {}".format(url))
         webbrowser.open(url)
         break
      time.sleep(1)
