dependencies:
  - matplotlib
  - jupyter-server-proxy
  - numpy
  - pandas
  - flask
  - flask-restful
  - flask-cors
  - requests
  - pycairo
  - pyarrow
  - pip
  - pip:
      - wrattler-python-service==0.7
      - wrattler-data-store==0.5.1
      - clevercsv
      - seaborn
  - R
