#!/bin/bash
http-server ${HOME}/wrattler/client/public -c-1 --cors &
wrattler-data-store &
wrattler-python-service &
export R_SERVICE_HOME="${HOME}/wrattler/server/R"
Rscript ${HOME}/wrattler/server/R/app.R &
cd ${HOME}/wrattler/aiassistants/server; dotnet bin/Debug/netcoreapp2.1/aiassistants.dll &
cd -
exec "$@"
